# Generated by Django 5.2.1 on 2025-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='place_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='place_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='place_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='place_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
